use_frameworks!

target 'WDTools_Example' do
  pod 'WDTools', :path => '../'

  target 'WDTools_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
